sudo: false
services:
- docker
language: node_js
node_js:
- 9
branches:
  only:
  - master
env:
  global:
  - secure: ATgnM2UWR8CeN9ZWkhW4knPAtG/vUeZBtGvx+kppwfjbnACfwFIPNu8EnwDZuJSTTBDx93zOX3dhr8zCaIg+cHsnHlBF6bzgXGSEini0W5iirDia4L/6GG8NThYt00oyHaALPHuAppHn/uB1Wt9TnZkwvhSpd4efsyDaICxDbZzka4KiKZNfZMhduAsyLh+CGVZ1l5nWucTddEhzfPExZheDMV6ns9chEmvcVGbXngT2QBxX8vL2FNuSII93Uf51K6UnYgL1J7AMO5R50cFOOC04HgRowtLhFLlPNutatPCPnKLGW0QdpAIpucPeM7O4Ydl+iYB8NTShZrDh3b6Z/WeqxGKsGTJdgZVN9iVDKKg9qZMMFbSq5T74JCMYh5CmTOIye4onjnkS2xhk6evYjKllRriH4fNiqFrlZMrDQghUBqaLlPVp4HZocR2hfR7GRRr6oVJT2x2caHJ+IqB6JWYkFZJkXIoEks/bSfaxMSF2cvpL6b8JUPpX+tn1YSHsply0ODPFQ/3YfDfBHJ93du9lMRKD4qyn5xbqlXotU5cRoi1Sj2n2SNQZjDkCQaEj/qdNztglX5Tj65gDOjMLaekoSQB5KdW/9WixcTnERsX/GtXWKdNY01V/rRbWIsTSysZp1CBmOxLGH4ozqoZKYwq2Jo4lvJSHldUOS95xJKo=
  - secure: kjJAe8wa2uqECQU7HgEFWsFBYIj/aOBM10IUcSQO0PAjZVohkwP54rDeSpxzdQO1zAENxkQ73CXnHGjv19BJzfIO1QY+2iVP+Z3++pwsfVxdZo/ebhwkXBK/LzqCWfKWmopS/RJwhkpdOdaFrr4TxdYvQBzBRfzMhNCJYkd4Fu2v5ygHXUoa4yFAITspJaLFJZpMKLfG/e114O1ii/Uqrz+STw9/w8CDT9PAmbvDw+nsvP6ZdnvcPQ8LsGktHf87lQ5/CcsznwbsVQ8oXWARh2mrbnvW1fZMVxLGhaH6vrPng+Khl9vpXoCI1DNqhIp13/53aIdIbZCwkKZiSoD7CEC50NXwA/1LEDvHxuvxoXyRPT13sQBS3rxPTKoG5tyVsTnQKX/D+qPfZCEVBJv+ESbkLajyb9Y7IuT+rjppA79SYpF1tyfMme50KboDHyi3ZBEM826FBxvGJ97VXfgIJal4SUbBGrG1DS348U7O13inh/fHhSPRShCHLxhHO7fIB6f1qmNe0cqnAeHLKvJ+Cgst4J/6JfPVYM1SvTUpri84bpg1pyvWfgVDVjYi0jLwbuzdI16Ne9tJNiyRMmIkW4+7X3ccXfmPyhe5jxeT3OyW/osFfXPqHH+hClSeDjlr7WCVpc+Cri8F/uACDhbIXKlSTIMJcoQ6+VDmWfsllhk=
  - secure: NR2mv2l04CZIt5rt65HJVsW5YWapQcohOtt8/jQJIWBzJoE7feM0/ZRSRtF8VBN2GI0xofAbbHN+x6a5VCaSH61LB9/xKxGePXrtlB0ih0sT0gfmJsYEysEx9qRI1MNiR8loHgvQM41E3QRNHqBjhHE3i4nKsvgWOwmo6jaYyVxTGQc8GdGx7mf6x0EggfSLC3HdQkEa6aIpLOUAoWlZssJ9BN2vTedd8E8Yf2xb9sskJtOt7XDQMmQ1e9LUEQi5n1wNHiR1V/Pwo1ybW6Be2qIZep4KOECGAHjw4QsUAYc94dH5GPnRnpcWf1gJldH8g3PGaPg42Mcj0jLt9ZKsjAmyeKByqZE0HCKUexU31GmwgmRWrptKbUdQrwGFRUswMndDqWM/YBmGXSa8HaEfy7F+nPfkF6KVuW5Op9fTZcOQ63eDocM+UsrOHDL2x6WIioVGn8quDDp1/XpzGkcwhwZNcohJ/9BsStHkHBYlQgh0ZKSsRCtyub6Y7BVY/6JcHE70hdqZeHlGX7777tY+cpnVs4Qdm4nOsn/3vSrsQk36YsCsNpx79P/w6DhE+YsvDx/To4Q4XeKnw6kzeziNe/cJPP9xhxMnKaUpv2bcs5nTPeBb8y2gQricfbxf81Mcj7R3gzo+xMeO3ktJ9LZ4kZy7xs45bvxgHk5cpWcRFGA=
  - COMMIT=${TRAVIS_COMMIT::8}
after_success:
- docker login -u $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=1545662258668/node1
- export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi'
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
before_install:
- openssl aes-256-cbc -K $encrypted_7dfb4f4e109f_key -iv $encrypted_7dfb4f4e109f_iv
  -in deploy_key.enc -out ./deploy_key -d


 deploy:
 provider: script
 skip_cleanup: true
 script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key nik@<34.73.211.231> ./deploy.sh
 on:
   branch: master
